### ISSUE TITLE
Unable to shut down executors if creation of Injector fails

### ISSUE THREAD

**Issue by bgooren** [skuzzle/guice-async-extension#7]
Hi!

... I'm back with another minor issue we see in development quite often :-)

When we are testing and one of our guice modules "fails" and the Injector creation errors out, we have lingering executor threads from guice async which we cannot cleanly shutdown. The only way to exit the jvm is by killing it.

This is because the executors are eagerly created when the `Injector` is built. When the `Injector` fails to complete construction, the executors have already been created and started.

Is it possible for you to add a `start` method to `GuiceAsyncService` (mirroring the `shutdown` method). To prevent breaking existing integrations, you could make this optional by adding a method to `GuiceAsync`: `enableFor(Binder binder, boolean autoStart)`.
The existing method would simply delegate to `enableFor(binder, true)`.

This way we can start the schedulers when our application is ready to start processing; This is certainly not always when the Injector is constructed.

**Comment by skuzzle** [comment]
Hi there,

I really appreciate your feedback and I'm happy to help you with this one.

I guess this actually boils down to 2 separate questions:
1. Should methods always be scheduled automatically when they are encountered?
2. How to properly react to errors during `Injector` creation

Regarding 1:
In my opinion, methods should always be automatically scheduled. Otherwise it creates too much overhead and counter intuitive behavior for the user.
However, I could imagine to invent some kind of flag (either globally or per-method, like `@Manually`) to state that this method is to be scheduled by a manual call to `start()`.  As methods are currently scheduled by the time they are encountered during `Injector` setup, it is not that simple to implement such a `start` method though. 

Regarding 2:
Two ideas here. 
Idea 1: all the schedlung should only be started (by the framework) when it is clear that the Injector is otherwise ready. Maybe this is exactly the distinction that is actually already implemented in [SchedulerTypeListener](https://github.com/skuzzle/guice-async-extension/blob/master/src/main/java/de/skuzzle/inject/async/schedule/SchedulerTypeListener.java)

Idea 2: If it is possible to react to `Injector` creation failures from within the framework, it would be pretty easy to shutdown the injector then. I don't know though if that is easily possible with the Guice API.

I consider this issue very relevant and valid but I'll need some time and maybe some more discussion to find a proper solution to this

**Comment by bgooren** [comment]
Hi!

Standard Guice does not offer any lifecycle tracking, which means  2.2 is not possible...

Regarding 1 I gave this some thought and have mixed feelings; In general I agree. However in practice I see that most scheduled methods we run actually depend on the "application being ready to process things".
For example: we have a web application which has it's own initialization, we have some Guice services that take some time to start up. We actually broadcast an `ApplicationStartedEvent` so listeners know they can begin work.

Another specific case that breaks for us right now is as follows.
We use guice-persist to manage JPA; It allows us to have scheduled methods which have both `@Scheduled` and `@Transactional`.
However, since guice-persist is not fully initialized (meaning: entity manager available) until its servlet filter is initialized, this leads to exceptions when scheduled tasks run right away.

In my mind it's quite normal to have some kind of application lifecycle with explicit start and stop; 
Currently we always have to remember 2 things when using scheduled methods:
- have outer scheduled method and inner protected method with `@Transactional` and only delegate to it once we have received `ApplicationStartedEvent`
- try to time (meaning: get lucky) startup so it doesn't coincide with exact scheduled time of methods

I did realize this is probably fixable if you let users provide their own executors (and not per method, but override the default executor for the whole module).
We could then simply provide an executor which caches executions when not started up yet, and gets out of the way once `ApplicationStartedEvent` is received.
Does that sound OK to you?

It's related to another pattern I've noticed: we have some custom error handling on scheduled method failure, and right now this means that for every scheduled method we provide an `@OnError` annotation. It would make my life easier if we could override the default error handler for the whole module, since we repeat the same annotation for every scheduled method right now.

**Comment by skuzzle** [comment]
This sounds reasonable. I created an extra ticket for allowing users to globally exchange the executor. I don't think that building a caching Executor should be proper soultion to this problem here though.

I have now build the possibility to configure some aspects of the scheduling behavior (for now, this is limited to the 'start manually' feature that we are discussing here). I'll give this stuff some more thoughts, but for now, it would work like this:

```
ScheduleProperties disableAutoScheduling = ScheduleProperties.defaultProperties()
                        .disableAutoScheduling();
Model scheduleModel = GuiceAsync.createModuleWithFeatures(
        ScheduleFeature.withProperties(disableAutoScheduling));
```

I almost forgot that I've been in the middle of a big refactoring that will lead to a major version change. That change is mostly about internal structure (see #5), to separate the handling of `@Async` and `@Scheduled` methods, because they are completely different things. 

Migration should be as simple as to adjust some imports but I try to provide a more detailled changelog and migration information when I release the version.

**Comment by skuzzle** [comment]
I have release version `2.0.0-beta` for you to try out if you like. Just let me know if you encounter any problems. I've also adjusted the wiki to reflect some changes that I made (mainly the [Getting Started](https://github.com/skuzzle/guice-async-extension/wiki/Getting-started) part)

**Comment by bgooren** [comment]
Hi - Thank you for looking into this, I will have a look and report back

**Comment by bgooren** [comment]
Hi Simon, I was doing some testing today with 2.0.0-beta; Regular operation (startup without issues, run scheduled tasks) still works perfect, and I can now gracefully handle failure to create the Injector. So thumbs up from me 👍

**Comment by skuzzle** [comment]
Great to hear. As no further changes are currently planned, I decided to release this as `2.0.0` to get rid of the `beta` flag. Fell free to use it in production and to report back any issues.
